# Recipe for an HE-ready Centos 8 docker
FROM centos:8

# Install general HElib pre-requisites
RUN yum -y update && \
    yum -y upgrade && \
    yum -y install epel-release && \
    yum -y group install "Development Tools" && \
    yum -y update && \
    yum -y install patchelf cmake wget python3 diffutils parallel

# Install bats-core (used for testing utils and examples)
RUN cd && \
    wget https://github.com/bats-core/bats-core/archive/v1.2.1.tar.gz && \
    tar xf v1.2.1.tar.gz && \
    cd bats-core-1.2.1 && \
    ./install.sh /usr/local

# Install Google Benchmarks (used for HElib benchmarks)
RUN cd && \
    wget https://github.com/google/benchmark/archive/v1.5.2.tar.gz && \
    tar xf v1.5.2.tar.gz && \
    cd benchmark-1.5.2 && \
    mkdir build && \
    cd build && \
    cmake -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DCMAKE_BUILD_TYPE=Release .. && \
    make -j4 && \
    make install

# Install NTL and GMP
RUN yum -y install gmp-devel && \
    curl -O "https://libntl.org/ntl-11.4.3.tar.gz" && \
    tar xf ntl-11.4.3.tar.gz && \
    cd ntl-11.4.3/src && \
    ./configure PREFIX=/usr/local SHARED=on NTL_GMP_LIP=on NTL_THREADS=on NTL_THREAD_BOOST=on GMP_PREFIX=/usr && \
    make -j4 && \
    make install 

# Script for building and testing HElib
COPY build_scripts/build_and_test_helib.sh /root

# Default script - Build and test HElib and all subprojects using package build
CMD ["/root/build_and_test_helib.sh", "-a"]
